name: Debug Issue Comment Event

on:
  issue_comment:
    types: [created, edited]

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Print event payload
        run: |
          echo "Event Payload:"
          cat $GITHUB_EVENT_PATH
